/* This code sample provides a starter kit to implement server side logic for your Teams App in JavaScript with code
 * snippets, refer to https://docs.microsoft.com/en-us/azure/azure-functions/functions-reference for complete Azure
 * Functions developer guide.
 */

const teamsfxServerSdk = require('teamsdev-server');

/**
 * This function handles requests sent from teamsfx client SDK.
 * The HTTP request should contain an SSO token in the header and any content in the body.
 * The SSO token should be queried from Teams client by teamsfx client SDK.
 * Before trigger this function, teamsfx binding would process the SSO token and generate teamsfx configuration.
 *
 * This function initializes the teamsfx Server SDK with the configuration and calls these APIs:
 * - getUserInfo() - Get the user's information from the received SSO token.
 * - getMicrosoftGraphClientWithUserIdentity() - Get a graph client to access user's Microsoft 365 data.
 *
 * The response contains multiple message blocks constructed into a JSON object, including:
 * - An echo of the request body.
 * - The display name encoded in the SSO token.
 * - Current user's Microsoft 365 profile if the user has consented.
 *
 * @param {Context} context - The Azure Functions context object.
 * @param {HttpRequest} req - The HTTP request.
 * @param {teamsfxConfig} config - The teamsfx configuration generated by teamsfx Binding.
 */
module.exports = async function (context, req, config) {
  context.log('JavaScript HTTP trigger function processed a request.');

  // Initialize response.
  const res = {
    status: 200,
    body: {}
  };

  // Put an echo into response body.
  res.body['receivedHTTPRequestBody'] = req.body || '';

  // Initialize teamsfx Server SDK with teamsfx configuration.
  let client;
  try {
    client = teamsfxServerSdk.teamsfx.getInstance(config);
  } catch(e) {
    context.log.error(e);
    res.status = 500;
    res.body['error'] = 'Fail to initialize teamsfx Server SDK.';
    return res;
  }

  // Query user's information from the authentication token.
  const currentUser = client.getUserInfo();
  if (currentUser && currentUser.displayName) {
    res.body['userInfoMessage'] = `User display name is ${currentUser.displayName}.`;
  } else {
    res.status = 400;
    res.body['userInfoMessage'] = 'Fail to get user display Name.';
    return res;
  }

  // Create a graph client to access user's Microsoft 365 data after user has consented.
  try {
    const graphClient = await client.getMicrosoftGraphClientWithUserIdentity(['.default']);
    const profile = await graphClient.api('/me').get();
    res.body['graphClientMessage'] = profile;
  } catch (e) {
    context.log.error(e);
    res.status = 500;
    res.body['graphClientMessage'] = 'Fail to get profile, maybe consent flow is required.';
    return res;
  }

  return res;
}
